timeout: 3

/DeepX OS
    protocol: limine
    path: boot():/boot/kernel.elf
    
    # Modulok a te Limine verziód szerint:
    module_path: boot():/initrd/hello.dxs
    module_cmdline: hello.dxs
    # A grafikai beállításaid (ha kellenek a szöveges módhoz):
    term_backend: text
    vga: on