timeout: 3
term_backend: text

/DeepX OS
    protocol: limine
    path: boot():/boot/kernel.elf
    vga: on
    module_path: boot():/initrd/hello.dxs
    module_cmdline: hello.dxs
    module_path: boot():/initrd/mountian.dxs
    module_cmdline: mountian.dxs
